apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  destination:
    namespace: foo
    server: https://kubernetes.default.svc
  project: project
  source:
    path: foo
    repoURL: https://github.com/robbiemcmichael/argocd-namespace-isolation.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
